"""Add student profile details

Revision ID: 623c56a1368a
Revises: 
Create Date: 2026-09-19 12:35:58.425567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623c56a1368a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('enrollment_schedule_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('enrollment_schedule_filename')
        batch_op.drop_column('semester')
        batch_op.drop_column('course_name')
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###
