"""Add extracted enrollment courses

Revision ID: 8b9c8da50446
Revises: 623c56a1368a
Create Date: 2026-09-19 14:16:06.244035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9c8da50446'
down_revision = '623c56a1368a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_courses', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('enrollment_courses')

    # ### end Alembic commands ###
